import '../home_page/widgets/rmjaseelsft_item_widget.dart';import '../home_page/widgets/userprofile1_item_widget.dart';import '../home_page/widgets/videolessons_item_widget.dart';import 'package:carousel_slider/carousel_slider.dart';import 'package:flutter/material.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';import 'package:trainee_s_future_tech/core/app_export.dart';
// ignore_for_file: must_be_immutable
class HomePage extends StatelessWidget {HomePage({Key? key}) : super(key: key);

int sliderIndex = 1;

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: Container(width: 547.h, decoration: AppDecoration.fillGray, child: Column(children: [SizedBox(height: 96.v), Expanded(child: SingleChildScrollView(child: Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 17.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [CustomImageView(imagePath: ImageConstant.imgMenu, height: 50.adaptSize, width: 50.adaptSize, onTap: () {onTapImgMenu(context);}), Padding(padding: EdgeInsets.only(left: 32.h), child: Text("Future Tech", style: theme.textTheme.displayMedium))]), SizedBox(height: 20.v), Padding(padding: EdgeInsets.only(right: 104.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Text("Hello,", style: theme.textTheme.displayMedium)), Padding(padding: EdgeInsets.only(left: 10.h, bottom: 3.v), child: Text("Naveed", style: CustomTextStyles.displayMediumLime700))]), Text("Let’s explore the lesson", style: theme.textTheme.headlineSmall), SizedBox(height: 37.v), Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 2.v), child: Text("Start Services", style: CustomTextStyles.headlineLargeOnPrimary_1)), CustomImageView(imagePath: ImageConstant.imgRiRemovebgPreview, height: 35.adaptSize, width: 35.adaptSize, margin: EdgeInsets.only(left: 8.h, top: 6.v))])]), CustomImageView(imagePath: ImageConstant.imgGrRemovebgPreview, height: 100.adaptSize, width: 100.adaptSize, margin: EdgeInsets.only(left: 32.h, top: 10.v, bottom: 51.v))])), SizedBox(height: 40.v), _buildVideoLessons(context), SizedBox(height: 32.v), _buildUserProfile(context), SizedBox(height: 10.v), Container(height: 10.v, margin: EdgeInsets.only(left: 167.h), child: AnimatedSmoothIndicator(activeIndex: sliderIndex, count: 1, axisDirection: Axis.horizontal, effect: ScrollingDotsEffect(spacing: 4, activeDotColor: appTheme.purple500, dotColor: theme.colorScheme.onPrimary, dotHeight: 10.v, dotWidth: 10.h))), SizedBox(height: 35.v), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("Lecture Panel", style: CustomTextStyles.headlineLargeOnPrimary_1)), SizedBox(height: 16.v), _buildRmJaseelSft(context)]))))])))); } 
/// Section Widget
Widget _buildVideoLessons(BuildContext context) { return SizedBox(height: 106.v, child: ListView.separated(padding: EdgeInsets.only(right: 1.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 15.h);}, itemCount: 4, itemBuilder: (context, index) {return VideolessonsItemWidget(onTapImgVideoLessonsImage: () {onTapImgVideoLessonsImage(context);});})); } 
/// Section Widget
Widget _buildUserProfile(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 3.h, right: 113.h), child: CarouselSlider.builder(options: CarouselOptions(height: 114.v, initialPage: 0, autoPlay: true, viewportFraction: 1.0, enableInfiniteScroll: false, scrollDirection: Axis.horizontal, onPageChanged: (index, reason) {sliderIndex = index;}), itemCount: 1, itemBuilder: (context, index, realIndex) {return Userprofile1ItemWidget();})); } 
/// Section Widget
Widget _buildRmJaseelSft(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 3.h, right: 113.h), child: ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 1.v);}, itemCount: 8, itemBuilder: (context, index) {return RmjaseelsftItemWidget();})); } 
/// Navigates to the videoLessonsScreen when the action is triggered.
onTapImgVideoLessonsImage(BuildContext context) { Navigator.pushNamed(context, AppRoutes.videoLessonsScreen); } 
/// Navigates to the drawerScreen when the action is triggered.
onTapImgMenu(BuildContext context) { Navigator.pushNamed(context, AppRoutes.drawerScreen); } 
 }
