import 'package:flutter/material.dart';import 'package:trainee_s_future_tech/core/app_export.dart';class DrawerScreen extends StatelessWidget {const DrawerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: Container(width: 348.h, padding: EdgeInsets.only(top: 77.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgBraRemovebgPreview201x348, height: 201.v, width: 348.h), SizedBox(height: 36.v), Padding(padding: EdgeInsets.only(left: 47.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgDateRange, height: 40.adaptSize, width: 40.adaptSize), GestureDetector(onTap: () {onTapTxtCalender(context);}, child: Padding(padding: EdgeInsets.only(left: 18.h, top: 2.v, bottom: 3.v), child: Text("Calender", style: theme.textTheme.headlineMedium)))])), SizedBox(height: 11.v), _buildPromotionVideoRow(context), SizedBox(height: 9.v), Padding(padding: EdgeInsets.only(left: 53.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgCall, height: 30.adaptSize, width: 30.adaptSize, margin: EdgeInsets.only(top: 9.v)), GestureDetector(onTap: () {onTapTxtContactUs(context);}, child: Padding(padding: EdgeInsets.only(left: 23.h, bottom: 5.v), child: Text("Contact Us", style: theme.textTheme.headlineMedium)))])), SizedBox(height: 32.v), Divider(color: appTheme.blueGray100), SizedBox(height: 14.v), Padding(padding: EdgeInsets.only(left: 57.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 40.adaptSize, width: 40.adaptSize), GestureDetector(onTap: () {onTapTxtSignOut(context);}, child: Padding(padding: EdgeInsets.only(left: 14.h, top: 2.v, bottom: 3.v), child: Text("Sign out", style: theme.textTheme.headlineMedium)))])), SizedBox(height: 27.v), Padding(padding: EdgeInsets.only(left: 57.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgSearch, height: 40.adaptSize, width: 40.adaptSize), GestureDetector(onTap: () {onTapTxtShare(context);}, child: Padding(padding: EdgeInsets.only(left: 15.h, bottom: 6.v), child: Text("Share", style: theme.textTheme.headlineMedium)))])), SizedBox(height: 5.v)])))); } 
/// Section Widget
Widget _buildPromotionVideoRow(BuildContext context) { return Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(left: 50.h, right: 17.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, crossAxisAlignment: CrossAxisAlignment.start, children: [Opacity(opacity: 0.44, child: CustomImageView(imagePath: ImageConstant.imgVector, height: 40.adaptSize, width: 40.adaptSize, margin: EdgeInsets.only(top: 3.v))), GestureDetector(onTap: () {onTapTxtPromotionVideo(context);}, child: Padding(padding: EdgeInsets.only(left: 16.h, bottom: 9.v), child: Text("Promotion video", style: theme.textTheme.headlineMedium)))]))); } 
/// Navigates to the calenderScreen when the action is triggered.
onTapTxtCalender(BuildContext context) { Navigator.pushNamed(context, AppRoutes.calenderScreen); } 
/// Navigates to the promationVideoScreen when the action is triggered.
onTapTxtPromotionVideo(BuildContext context) { Navigator.pushNamed(context, AppRoutes.promationVideoScreen); } 
/// Navigates to the contactUsScreen when the action is triggered.
onTapTxtContactUs(BuildContext context) { Navigator.pushNamed(context, AppRoutes.contactUsScreen); } 
/// Navigates to the signOutScreen when the action is triggered.
onTapTxtSignOut(BuildContext context) { Navigator.pushNamed(context, AppRoutes.signOutScreen); } 
/// Navigates to the shareScreen when the action is triggered.
onTapTxtShare(BuildContext context) { Navigator.pushNamed(context, AppRoutes.shareScreen); } 
 }
